name: Build & Push to DockerHub (Manual Docker Commands)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t simple-docker-app .

      - name: Tag Docker Image
        run: |
          docker tag simple-docker-app ${{ secrets.DOCKER_USERNAME }}/simple-docker-app:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-docker-app:latest

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            echo "Logging into DockerHub..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/simple-docker-app:latest

            echo "Stopping & removing old container..."
            docker stop simple-docker-app || true
            docker rm simple-docker-app || true

            echo "Running new container..."
            docker run -d --name simple-docker-app -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/simple-docker-app:latest
          EOF
